### ISSUE TITLE
Makefile について

### ISSUE THREAD

**Issue by Okdenn** [MasatakaHamada/episode#1]
もしすでにご存じだったりしたら申し訳ないのですが，TeXファイルをコンパイルするとき，いちいち "platex main platex main dvipdfmx main"とか打ってるとつらいと思うので，Makefile を作ると便利だと思います(しかし自分も，具体的に教えろと言われても厳しい程度のにわかである)．
( http://www.ie.u-ryukyu.ac.jp/~e085739/c.makefile.tuts.html
http://shin.hateblo.jp/entry/2012/05/26/231036
https://texwiki.texjp.org/?Make
とか?)

**Comment by MasatakaHamada** [comment]
ありがとうございます．
私は普段TeXworks editorを使っており，タイプセットにはptex2pdfを用いているので，あまり気にしていませんでした．
https://texwiki.texjp.org/?TeXworks
https://texwiki.texjp.org/?ptex2pdf
ただ，おっしゃっていることは大変よくわかりますので，episodeにあるREADME.mdの”main.texをコンパイルする”の部分を次のように書き換えたいと思います．いかがでしょうか？

> platex main  
> platex main  
> dvipdfmx main  
> 等でできる．2回コンパイルしないと目次が更新されない（定理等の番号付けが2回コンパイルしないと反映されないのと同じ理屈）．ただし，いちいちこれを打つのも大変なので，Makefileを使うと良いかもしれない．詳しくは
> https://texwiki.texjp.org/?Make

**Comment by Okdenn** [comment]
ありがとうございます．

いえいえ，もしターミナル等でコンパイルされるようでしたら，と思ってだったので，特に直すなどはしていただかなくても大丈夫です．

**Comment by MasatakaHamada** [comment]
わかりました．
README.mdは，自分のためというより今後編集する人のために作ったつもりだったので，上記の修正は行いたいと思います．

**Comment by Okdenn** [comment]
わかりました，ありがとうございますm(_ _)m
