### ISSUE TITLE
目次以降のページ番号の位置がおかしい

### ISSUE THREAD

**Issue by MasatakaHamada** [MasatakaHamada/episode#12]
気付いている人もいるかもしれませんが，eπisode Vol.7は**目次以降のページ番号の位置が逆**になっています．電子版だとわかりづらいですが，本来見開きで外側に来るはずの，例えば

>無限の大きさ比べ(濱田)　19
>20　無限の大きさ比べ(濱田)

が見開きだと内側に来てしまっています．

原因は「ページ番号の位置を，目次を含めた全体ではなく**本文のページ数の偶奇**により決定しているため，まえがきが2ページに渡ったことでズレが生じたから」です．

解決策は大きく2つ．

1. まえがきを1ページに収める（今回はページ数調整でまえがきを増やした，という事情もある）
2. TeXファイル等を適当に書き換える（どこを変えればよいかは，少なくとも私にはわからない）

とりあえず，issue として投げておきます．

**Comment by Okdenn** [comment]
多分ですが，ページ数をどこに振るかを指示している場所は，kyouritu.cls の1282-1287行目付近の
`\def\ps@plain{\let\@mkboth\@gobbletwo
   \let\ps@jpl@in\ps@plain
   \def\@oddhead{\KBpagenumfont\hfil\thepage}
   \let\@oddfoot\@empty%
   \def\@evenhead{\KBpagenumfont{\thepage}\hfil}
   \let\@evenfoot\@empty}
`
のような気がします．
1. 

1.

**Comment by Okdenn** [comment]
多分ですが，ページ数をどこに振るかを指示している場所は，kyouritu.cls の1282-1287行目付近の
```tex
\def\ps@plain{\let\@mkboth\@gobbletwo 
\let\ps@jpl@in\ps@plain
\def\@oddhead{\KBpagenumfont\hfil\thepage}
\let\@oddfoot\@empty%
\def\@evenhead{\KBpagenumfont{\thepage}\hfil}
\let\@evenfoot\@empty}
```
のような気がします．

1. `\@oddhead` やらなんやらの内部構造を知らないのでアレですが，これをオーバーライドするというのが一手（おそらくかなり危険）
2. なんらかの他のコマンドで，「全体のページ数」をカウントしその偶奇でここのヘッダを変えるのが一手（ただ他にも`\@oddhead`を使っている部分は腐るほどあり，どれを変えるべきかの判断が不明）
3. あとは目次の偶奇によって空白ページを挟むかを決めるコードを加えるのが一手かと思います．
これについては，http://denki.nara-edu.ac.jp/~yabu/soft/tex/y-jbook.sty より，
```tex
% 次の \ifodd は、目次のページが奇数で終わるときに白紙のページを
% 付け加えるために作ったが、\cleardoublepage をカスタマイズしたので
% その必要はなくなった。
%\ifodd \c@page \newpage \thispagestyle{empty}\newpage \fi
%\if@restonecol\twocolumn\fi}
```
というものを見つけました．

**Comment by Okdenn** [comment]
ここらへんとかですかね……
https://oversleptabit.com/archives/428
これを`\input{maegaki}`の後に入れるとか??
http://d.hatena.ne.jp/sogolosphere/20081128/1227891158

**Comment by Okdenn** [comment]
しかしどうして同じファイルなのにトータルのページ数を数えていないんだろうと思ったら，想像以上に問題が根深いことがわかりました．
[LaTeXで現在のページ番号を取得・出力する話](https://qiita.com/zr_tex8r/items/d9970aa8f4558de33dbe)
