### ISSUE TITLE
README.md が2つある

### ISSUE THREAD

**Issue by Okdenn** [MasatakaHamada/episode#15]
些細っちゃ些細なことなのですが，同じ episode プロジェクト内に README.md が2つあります．
1つは直下の編集者向け，もう1つは manuscript フォルダ内の記事作成者向けのものです．
main.tex をコンパイルする際に manuscript 内のファイルを直下に移動させようとして気づきました．
もしよろしければ何らかの対処をよろしくお願いいたします．

**Comment by MasatakaHamada** [comment]
実はこうしているのには（些細な）理由があります．

ファイル名を `readme.md` や `README.md` とすると，それが置かれているレポジトリが表示されたときにその内容が表示されるんですよね．

![image](https://user-images.githubusercontent.com/37033024/42513259-6cd304a2-8491-11e8-8125-c2cdf45d02a5.png)

ファイル名に `readme` を使わなくても上のようにできる方法ってあるんでしょうか...？

**Comment by Okdenn** [comment]
まぁ多分そういう理由だろうなぁとは思っていました．
パッと調べたところありませんね......
今いろいろやってみたところ，おそらく前から拡張子までの部分完全一致で判断しているのか，`README.md_` （最後にアンダーバー）でも表示はされることがわかりました．ただしマークダウンは働きません．
https://github.com/Okdenn/HowtoGitHub
![260](https://user-images.githubusercontent.com/35955369/42514298-06d33994-8494-11e8-8833-a9275143696a.png)

1README.md -> fail
READMEE.md -> fail
でした．

**Comment by Okdenn** [comment]
気にしないのが一手，
1つのREADME に統一して，編集者用と書く人用に項目を分け，必要に応じて飛べるようにするのが一手，
そもそも書く人々ないし編集者は Markdown で見る必要があるんだろうか（見てるんだろうか），txt か PDF，偽 Markdown で十分では，というのが一手ですね......

**Comment by Okdenn** [comment]
編集者にLinuxを使わせるという手もあります（おそらく大文字小文字区別するので）．
単純に，manuscript からファイルを直下にどばーした時に**うっかり** README.md まで上書く危険があるのが怖いという程度なので，このプロジェクト内には 異なる相手への README.md が2つあるので上書きには注意，ということだけ編集者になる人に注意喚起すれば十分かな，とは思います．
